repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
        args: ["--maxkb=1500"]
        exclude: ^test_ui/play_integration/game_screenshots/.*$
    -   id: check-ast
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        args: ["--line-length=110"]
        language_version: python3
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: ["--max-line-length=110"]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: "v5.10.1"
    hooks:
    -   id: isort
        args: ["--profile=black", "--line-length=100"]
